name: Generate Snake Game

on:
  # Run automatically on a schedule.
  schedule:
    # Runs every 24 hours
    - cron: "0 0 * * *"

  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Generate the snake
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Upload the snake images
      - name: Upload Snake Game Images
        uses: actions/upload-artifact@v2
        with:
          name: snake-game-images
          path: dist/
